#!/usr/bin/env python3
"""
generate_launch.py

Reads config/dataflow.yaml and generates launch/perception.launch.py
as a ROS 2 ComposableNode launch file.

Each process in dataflow.yaml becomes a separate ComposableNodeContainer
(its own OS process). Nodes within the same container communicate via
zero-copy intra-process callbacks; nodes in different containers communicate
via DDS.

Usage:
    python3 scripts/generate_launch.py [--dataflow config/dataflow.yaml]
                                       [--output  launch/perception.launch.py]
"""

import argparse
import sys
from pathlib import Path

import yaml

LAUNCH_HEADER = '''\
# AUTO-GENERATED by scripts/generate_launch.py
# Source: {source}
# Do not edit by hand — edit config/dataflow.yaml and re-run generate_launch.py

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, SetEnvironmentVariable
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import ComposableNodeContainer
from launch_ros.descriptions import ComposableNode
from launch_ros.substitutions import FindPackageShare


def generate_launch_description() -> LaunchDescription:
    pkg_share = FindPackageShare("traversability_generator")

    use_sim_time_arg = DeclareLaunchArgument(
        "use_sim_time", default_value="false",
        description="Use simulation clock"
    )
    use_sim_time = LaunchConfiguration("use_sim_time")

    # ── CycloneDDS (zero-copy intra-host via shared memory when enabled)
    cyclone_cfg = SetEnvironmentVariable(
        "CYCLONEDDS_URI",
        PathJoinSubstitution([pkg_share, "config/cyclonedds.xml"]),
    )
    rmw_impl = SetEnvironmentVariable(
        "RMW_IMPLEMENTATION", "rmw_cyclonedds_cpp"
    )

    # ── One ComposableNodeContainer per process (auto-generated from dataflow.yaml) ──
'''

LAUNCH_FOOTER = '''\

    return LaunchDescription([
        use_sim_time_arg,
        rmw_impl,
        cyclone_cfg,
{containers}
    ])
'''


def render_remappings(node: dict) -> str:
    remappings = []
    for port in node.get("inputs", []) + node.get("outputs", []):
        remappings.append(f'("{port["name"]}", "{port["topic"]}")')
    return ",\n                ".join(remappings)


def snake_to_camel(name: str) -> str:
    return "".join(word.capitalize() for word in name.split("_"))


def node_package(node_id: str) -> str:
    """Return the ament package name for a node ID (strips trailing _node)."""
    return node_id[:-5] if node_id.endswith("_node") else node_id


def render_composable_node(node: dict, indent: str = "        ") -> str:
    node_id = node["id"]
    plugin = node.get(
        "plugin",
        f"traversability_generator::{snake_to_camel(node_id)}",
    )
    params_file = node.get("params", "")
    package = node.get("package") or node_package(node_id)

    i = indent
    i2 = indent + "    "

    if params_file:
        params = (
            f'{i}    parameters=[\n'
            f'{i2}    {{"use_sim_time": use_sim_time}},\n'
            f'{i2}    PathJoinSubstitution([pkg_share, "{params_file}"]),\n'
            f'{i}    ],\n'
        )
    else:
        params = f'{i}    parameters=[{{"use_sim_time": use_sim_time}}],\n'

    remappings = render_remappings(node)

    return (
        f'{i}ComposableNode(\n'
        f'{i}    package="{package}",\n'
        f'{i}    plugin="{plugin}",\n'
        f'{i}    name="{node_id}",\n'
        f'{i}    namespace="",\n'
        f'{params}'
        f'{i}    remappings=[\n'
        f'{i}        {remappings},\n'
        f'{i}    ],\n'
        f'{i}),\n'
    )


def render_container(proc: dict) -> str:
    proc_id = proc["id"]
    executable = proc.get("executable", proc_id)
    operators = [n for n in proc.get("nodes", [])
                 if n.get("type", "operator") == "operator"]

    node_lines = "".join(render_composable_node(n) for n in operators)

    return (
        f'    # ── {proc_id}\n'
        f'    {proc_id}_container = ComposableNodeContainer(\n'
        f'        name="{executable}_container",\n'
        f'        namespace="",\n'
        f'        package="rclcpp_components",\n'
        f'        executable="component_container",\n'
        f'        composable_node_descriptions=[\n'
        f'{node_lines}'
        f'        ],\n'
        f'        output="screen",\n'
        f'    )\n'
    )


def generate(dataflow_path: Path, output_path: Path) -> None:
    with open(dataflow_path) as f:
        dataflow = yaml.safe_load(f)

    lines = [LAUNCH_HEADER.format(source=dataflow_path)]

    if "processes" in dataflow:
        container_names = []
        for proc in dataflow["processes"]:
            lines.append(render_container(proc))
            container_names.append(f"        {proc['id']}_container,")
    else:
        # Flat schema fallback: single container
        operators = [n for n in dataflow["nodes"] if n["type"] == "operator"]
        lines.append('    single_container = ComposableNodeContainer(\n')
        lines.append('        name="traversability_container",\n')
        lines.append('        namespace="",\n')
        lines.append('        package="rclcpp_components",\n')
        lines.append('        executable="component_container",\n')
        lines.append('        composable_node_descriptions=[\n')
        for node in operators:
            lines.append(render_composable_node(node))
        lines.append('        ],\n')
        lines.append('        output="screen",\n')
        lines.append('    )\n')
        container_names = ["        single_container,"]

    containers_str = "\n".join(container_names)
    lines.append(LAUNCH_FOOTER.format(containers=containers_str))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("".join(lines), encoding="utf-8")
    print(f"[generate_launch] wrote {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataflow", default="config/dataflow.yaml")
    parser.add_argument("--output", default="launch/perception.launch.py")
    args = parser.parse_args()

    dataflow_path = Path(args.dataflow)
    if not dataflow_path.exists():
        print(f"ERROR: {dataflow_path} not found", file=sys.stderr)
        sys.exit(1)

    generate(dataflow_path, Path(args.output))


if __name__ == "__main__":
    main()
