#!/usr/bin/env python3
"""
generate_launch.py

Reads config/dataflow.yaml and generates launch/perception.launch.py
as a ROS 2 ComposableNode launch file.

Usage:
    python3 scripts/generate_launch.py [--dataflow config/dataflow.yaml]
                                       [--output  launch/perception.launch.py]
"""

import argparse
import sys
from pathlib import Path

import yaml

LAUNCH_HEADER = '''\
# AUTO-GENERATED by scripts/generate_launch.py
# Source: {source}
# Do not edit by hand — edit config/dataflow.yaml and re-run generate_launch.py

import os
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, SetEnvironmentVariable
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import ComposableNodeContainer
from launch_ros.descriptions import ComposableNode
from launch_ros.substitutions import FindPackageShare


def generate_launch_description() -> LaunchDescription:
    pkg_share = FindPackageShare("traversability_generator")

    use_sim_time_arg = DeclareLaunchArgument(
        "use_sim_time", default_value="false",
        description="Use simulation clock"
    )
    use_sim_time = LaunchConfiguration("use_sim_time")

    # ── CycloneDDS shared memory (zero-copy for PointCloud2/Image on localhost)
    cyclone_cfg = SetEnvironmentVariable(
        "CYCLONEDDS_URI",
        PathJoinSubstitution([pkg_share, "config/cyclonedds.xml"]),
    )
    rmw_impl = SetEnvironmentVariable(
        "RMW_IMPLEMENTATION", "rmw_cyclonedds_cpp"
    )

    # ── Composable nodes (auto-generated from dataflow.yaml) ──────────────
'''

LAUNCH_FOOTER = '''\

    container = ComposableNodeContainer(
        name="traversability_container",
        namespace="",
        package="rclcpp_components",
        executable="component_container",
        composable_node_descriptions=composable_nodes,
        output="screen",
    )

    return LaunchDescription([
        use_sim_time_arg,
        rmw_impl,
        cyclone_cfg,
        container,
    ])
'''


def render_remappings(node: dict) -> str:
    remappings = []
    for port in node.get("inputs", []) + node.get("outputs", []):
        remappings.append(f'("{port["name"]}", "{port["topic"]}")')
    return ",\n                ".join(remappings)


def snake_to_camel(name: str) -> str:
    return "".join(word.capitalize() for word in name.split("_"))


def render_composable_node(node: dict) -> str:
    node_id = node["id"]
    plugin = node.get(
        "plugin",
        f"traversability_generator::{snake_to_camel(node_id)}",
    )
    params_file = node.get("params", "")

    if params_file:
        params = (
            f'            parameters=[\n'
            f'                {{"use_sim_time": use_sim_time}},\n'
            f'                PathJoinSubstitution([pkg_share, "{params_file}"]),\n'
            f'            ],\n'
        )
    else:
        params = '            parameters=[{"use_sim_time": use_sim_time}],\n'

    remappings = render_remappings(node)

    return (
        f'        ComposableNode(\n'
        f'            package="traversability_generator",\n'
        f'            plugin="{plugin}",\n'
        f'            name="{node_id}",\n'
        f'            namespace="",\n'
        f'{params}'
        f'            remappings=[\n'
        f'                {remappings},\n'
        f'            ],\n'
        f'        ),\n'
    )


def generate(dataflow_path: Path, output_path: Path) -> None:
    with open(dataflow_path) as f:
        dataflow = yaml.safe_load(f)

    operators = [n for n in dataflow["nodes"] if n["type"] == "operator"]

    lines = [LAUNCH_HEADER.format(source=dataflow_path)]
    lines.append("    composable_nodes = [\n")
    for node in operators:
        lines.append(render_composable_node(node))
    lines.append("    ]\n")
    lines.append(LAUNCH_FOOTER)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("".join(lines))
    print(f"[generate_launch] wrote {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataflow", default="config/dataflow.yaml")
    parser.add_argument("--output", default="launch/perception.launch.py")
    args = parser.parse_args()

    dataflow_path = Path(args.dataflow)
    if not dataflow_path.exists():
        print(f"ERROR: {dataflow_path} not found", file=sys.stderr)
        sys.exit(1)

    generate(dataflow_path, Path(args.output))


if __name__ == "__main__":
    main()
