# AUTO-GENERATED by scripts/generate_launch.py
# Source: config\dataflow.yaml
# Do not edit by hand — edit config/dataflow.yaml and re-run generate_launch.py

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, SetEnvironmentVariable
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import ComposableNodeContainer
from launch_ros.descriptions import ComposableNode
from launch_ros.substitutions import FindPackageShare


def generate_launch_description() -> LaunchDescription:
    pkg_share = FindPackageShare("traversability_generator")

    use_sim_time_arg = DeclareLaunchArgument(
        "use_sim_time", default_value="false",
        description="Use simulation clock"
    )
    use_sim_time = LaunchConfiguration("use_sim_time")

    # ── CycloneDDS shared memory (zero-copy for PointCloud2/Image on localhost)
    cyclone_cfg = SetEnvironmentVariable(
        "CYCLONEDDS_URI",
        PathJoinSubstitution([pkg_share, "config/cyclonedds.xml"]),
    )
    rmw_impl = SetEnvironmentVariable(
        "RMW_IMPLEMENTATION", "rmw_cyclonedds_cpp"
    )

    # ── Composable nodes (auto-generated from dataflow.yaml) ──────────────
    composable_nodes = [
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::CameraPreprocessNode",
            name="camera_preprocess_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/camera_preprocess.yaml"]),
            ],
            remappings=[
                ("image_raw", "/camera/image_raw"),
                ("camera_info", "/camera/camera_info"),
                ("image_rect", "/camera/image_rect"),
                ("camera_info_rect", "/camera/camera_info_rect"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::LidarAggregatorNode",
            name="lidar_aggregator_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/lidar_aggregator.yaml"]),
            ],
            remappings=[
                ("points_raw", "/lidar/points_raw"),
                ("points_aggregated", "/lidar/points_aggregated"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::LidarPreprocessNode",
            name="lidar_preprocess_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/lidar_preprocess.yaml"]),
            ],
            remappings=[
                ("points_aggregated", "/lidar/points_aggregated"),
                ("imu", "/imu/data"),
                ("tf", "/tf"),
                ("points_filtered", "/lidar/points_filtered"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::LidarGroundFilterNode",
            name="lidar_ground_filter_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/lidar_ground_filter.yaml"]),
            ],
            remappings=[
                ("points_filtered", "/lidar/points_filtered"),
                ("points_ground_removed", "/lidar/points_ground_removed"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::ElevationMappingNode",
            name="elevation_mapping_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/elevation_mapping.yaml"]),
            ],
            remappings=[
                ("points_ground_removed", "/lidar/points_ground_removed"),
                ("odometry", "/ego/odometry"),
                ("tf", "/tf"),
                ("elevation_map", "/terrain/elevation_map"),
                ("slope_map", "/terrain/slope_map"),
                ("roughness_map", "/terrain/roughness_map"),
                ("obstacle_map", "/terrain/obstacle_map"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::SegmentationNode",
            name="segmentation_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/segmentation.yaml"]),
            ],
            remappings=[
                ("image_rect", "/camera/image_rect"),
                ("seg_mask", "/segmentation/mask"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::LidarProjectionNode",
            name="lidar_projection_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/lidar_projection.yaml"]),
            ],
            remappings=[
                ("points_ground_removed", "/lidar/points_ground_removed"),
                ("projected_depth", "/lidar/projected_depth"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::SemanticLiftingNode",
            name="semantic_lifting_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/semantic_lifting.yaml"]),
            ],
            remappings=[
                ("seg_mask", "/segmentation/mask"),
                ("projected_depth", "/lidar/projected_depth"),
                ("camera_info_rect", "/camera/camera_info_rect"),
                ("semantic_points", "/terrain/semantic_points"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::BevFusionNode",
            name="bev_fusion_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/bev_fusion.yaml"]),
            ],
            remappings=[
                ("elevation_map", "/terrain/elevation_map"),
                ("slope_map", "/terrain/slope_map"),
                ("roughness_map", "/terrain/roughness_map"),
                ("obstacle_map", "/terrain/obstacle_map"),
                ("semantic_points", "/terrain/semantic_points"),
                ("feature_grid", "/bev/feature_grid"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::TemporalGridFusionNode",
            name="temporal_grid_fusion_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/temporal_grid.yaml"]),
            ],
            remappings=[
                ("feature_grid", "/bev/feature_grid"),
                ("stable_grid", "/bev/stable_grid"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::TraversabilityCostmapNode",
            name="traversability_costmap_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/traversability_costmap.yaml"]),
            ],
            remappings=[
                ("stable_grid", "/bev/stable_grid"),
                ("traversability_grid", "/world/traversability_grid"),
                ("planner_costmap", "/planner/costmap"),
            ],
        ),
    ]

    container = ComposableNodeContainer(
        name="traversability_container",
        namespace="",
        package="rclcpp_components",
        executable="component_container",
        composable_node_descriptions=composable_nodes,
        output="screen",
    )

    return LaunchDescription([
        use_sim_time_arg,
        rmw_impl,
        cyclone_cfg,
        container,
    ])
