# AUTO-GENERATED by scripts/generate_launch.py
# Source: config\dataflow.yaml
# Do not edit by hand — edit config/dataflow.yaml and re-run generate_launch.py

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, SetEnvironmentVariable
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import ComposableNodeContainer
from launch_ros.descriptions import ComposableNode
from launch_ros.substitutions import FindPackageShare


def generate_launch_description() -> LaunchDescription:
    pkg_share = FindPackageShare("traversability_generator")

    use_sim_time_arg = DeclareLaunchArgument(
        "use_sim_time", default_value="false",
        description="Use simulation clock"
    )
    use_sim_time = LaunchConfiguration("use_sim_time")

    # ── CycloneDDS (zero-copy intra-host via shared memory when enabled)
    cyclone_cfg = SetEnvironmentVariable(
        "CYCLONEDDS_URI",
        PathJoinSubstitution([pkg_share, "config/cyclonedds.xml"]),
    )
    rmw_impl = SetEnvironmentVariable(
        "RMW_IMPLEMENTATION", "rmw_cyclonedds_cpp"
    )

    # ── One ComposableNodeContainer per process (auto-generated from dataflow.yaml) ──
    # ── camera_preprocessor
    camera_preprocessor_container = ComposableNodeContainer(
        name="camera_preprocessor_container",
        namespace="",
        package="rclcpp_components",
        executable="component_container",
        composable_node_descriptions=[
        ComposableNode(
            package="camera_preprocess",
            plugin="traversability_generator::CameraBranchNode",
            name="camera_branch",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/camera_preprocess.yaml"]),
            ],
            remappings=[
                ("image_raw", "/camera/image_raw"),
                ("camera_info", "/camera/camera_info"),
                ("image_rect", "/camera/image_rect"),
                ("camera_info_rect", "/camera/camera_info_rect"),
            ],
        ),
        ComposableNode(
            package="segmentation",
            plugin="traversability_generator::SemanticSegmentationNode",
            name="semantic_segmentation_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/segmentation.yaml"]),
            ],
            remappings=[
                ("image_rect", "/camera/image_rect"),
                ("seg_mask", "/segmentation/mask"),
            ],
        ),
        ],
        output="screen",
    )
    # ── lidar_preprocessor
    lidar_preprocessor_container = ComposableNodeContainer(
        name="lidar_preprocessor_container",
        namespace="",
        package="rclcpp_components",
        executable="component_container",
        composable_node_descriptions=[
        ComposableNode(
            package="lidar_aggregator",
            plugin="traversability_generator::LidarAggregatorNode",
            name="lidar_aggregator_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/lidar_aggregator.yaml"]),
            ],
            remappings=[
                ("points_raw", "/lidar/points_raw"),
                ("points_aggregated", "/lidar/points_aggregated"),
            ],
        ),
        ComposableNode(
            package="lidar_preprocess",
            plugin="traversability_generator::LidarPreprocessNode",
            name="lidar_preprocess_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/lidar_preprocess.yaml"]),
            ],
            remappings=[
                ("points_aggregated", "/lidar/points_aggregated"),
                ("imu", "/imu/data"),
                ("tf", "/tf"),
                ("points_filtered", "/lidar/points_filtered"),
            ],
        ),
        ComposableNode(
            package="terrain_model",
            plugin="traversability_generator::TerrainModelNode",
            name="terrain_model_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/terrain_model.yaml"]),
            ],
            remappings=[
                ("points_filtered", "/lidar/points_filtered"),
                ("odometry", "/ego/odometry"),
                ("tf", "/tf"),
                ("elevation_map", "/terrain/elevation_map"),
                ("slope_map", "/terrain/slope_map"),
                ("roughness_map", "/terrain/roughness_map"),
                ("obstacle_map", "/terrain/obstacle_map"),
                ("points_no_tall_objects", "/lidar/points_no_tall_objects"),
            ],
        ),
        ComposableNode(
            package="lidar_projection",
            plugin="traversability_generator::LidarProjectionNode",
            name="lidar_projection_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/lidar_projection.yaml"]),
            ],
            remappings=[
                ("points_no_tall_objects", "/lidar/points_no_tall_objects"),
                ("points_projection", "/lidar/points_projection"),
                ("projected_depth", "/lidar/projected_depth"),
            ],
        ),
        ],
        output="screen",
    )
    # ── terrain_modeler
    terrain_modeler_container = ComposableNodeContainer(
        name="terrain_modeler_container",
        namespace="",
        package="rclcpp_components",
        executable="component_container",
        composable_node_descriptions=[
        ComposableNode(
            package="semantic_lifting",
            plugin="traversability_generator::SemanticLiftingNode",
            name="semantic_lifting_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/semantic_lifting.yaml"]),
            ],
            remappings=[
                ("seg_mask", "/segmentation/mask"),
                ("projected_depth", "/lidar/projected_depth"),
                ("tf", "/tf"),
                ("semantic_points", "/terrain/semantic_points"),
            ],
        ),
        ComposableNode(
            package="bev_fusion",
            plugin="traversability_generator::BevFusionNode",
            name="bev_fusion_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/bev_fusion.yaml"]),
            ],
            remappings=[
                ("elevation_map", "/terrain/elevation_map"),
                ("slope_map", "/terrain/slope_map"),
                ("roughness_map", "/terrain/roughness_map"),
                ("obstacle_map", "/terrain/obstacle_map"),
                ("semantic_points", "/terrain/semantic_points"),
                ("feature_grid", "/bev/feature_grid"),
            ],
        ),
        ComposableNode(
            package="temporal_grid",
            plugin="traversability_generator::TemporalGridFusionNode",
            name="temporal_grid_fusion_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/temporal_grid.yaml"]),
            ],
            remappings=[
                ("feature_grid", "/bev/feature_grid"),
                ("odometry", "/ego/odometry"),
                ("stable_grid", "/bev/stable_grid"),
            ],
        ),
        ComposableNode(
            package="traversability_costmap",
            plugin="traversability_generator::TraversabilityCostmapNode",
            name="traversability_costmap_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/traversability_costmap.yaml"]),
            ],
            remappings=[
                ("stable_grid", "/bev/stable_grid"),
                ("costmap", "/costmap"),
            ],
        ),
        ],
        output="screen",
    )

    return LaunchDescription([
        use_sim_time_arg,
        rmw_impl,
        cyclone_cfg,
        camera_preprocessor_container,
        lidar_preprocessor_container,
        terrain_modeler_container,
    ])
