# AUTO-GENERATED by scripts/generate_launch.py
# Source: config/dataflow.yaml
# Do not edit by hand — edit config/dataflow.yaml and re-run scripts/generate_launch.py

import os
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, SetEnvironmentVariable
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import ComposableNodeContainer
from launch_ros.descriptions import ComposableNode
from launch_ros.substitutions import FindPackageShare


def generate_launch_description() -> LaunchDescription:
    pkg_share = FindPackageShare("traversability_generator")

    use_sim_time_arg = DeclareLaunchArgument(
        "use_sim_time", default_value="false",
        description="Use simulation clock"
    )
    use_sim_time = LaunchConfiguration("use_sim_time")

    # ── CycloneDDS shared memory (zero-copy for PointCloud2/Image on localhost)
    cyclone_cfg = SetEnvironmentVariable(
        "CYCLONEDDS_URI",
        PathJoinSubstitution([pkg_share, "config/cyclonedds.xml"]),
    )
    rmw_impl = SetEnvironmentVariable(
        "RMW_IMPLEMENTATION", "rmw_cyclonedds_cpp"
    )

    # ── Composable nodes (auto-generated from dataflow.yaml) ──────────────
    composable_nodes = [
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::LidarPreprocessNode",
            name="lidar_preprocess_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/lidar_preprocess.yaml"]),
            ],
            remappings=[
                ("points_raw", "/lidar/raw"),
                ("imu", "/imu/data"),
                ("points_proc", "/lidar/proc"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::CameraPreprocessNode",
            name="camera_preprocess_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/camera_preprocess.yaml"]),
            ],
            remappings=[
                ("image_raw", "/camera/image_raw"),
                ("camera_info", "/camera/camera_info"),
                ("image_proc", "/camera/proc"),
                ("camera_info_proc", "/camera/proc/camera_info"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::SensorSyncNode",
            name="sensor_sync_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/sensor_sync.yaml"]),
            ],
            remappings=[
                ("points_proc", "/lidar/proc"),
                ("image_proc", "/camera/proc"),
                ("odom", "/odom"),
                ("lidar_synced", "/sync/lidar_points"),
                ("image_synced", "/sync/camera_image"),
                ("ego_pose_synced", "/sync/ego_pose"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::ElevationMappingNode",
            name="elevation_mapping_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/elevation_mapping.yaml"]),
            ],
            remappings=[
                ("lidar_synced", "/sync/lidar_points"),
                ("odom", "/odom"),
                ("elevation_map", "/elevation_map"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::DepthGenerationNode",
            name="depth_generation_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/depth_generation.yaml"]),
            ],
            remappings=[
                ("lidar_synced", "/sync/lidar_points"),
                ("image_synced", "/sync/camera_image"),
                ("camera_info_proc", "/camera/proc/camera_info"),
                ("depth_dense", "/depth/dense"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::SegmentationNode",
            name="segmentation_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/segmentation.yaml"]),
            ],
            remappings=[
                ("image_synced", "/sync/camera_image"),
                ("depth_dense", "/depth/dense"),
                ("seg_mask", "/seg/mask"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::BevProjectionNode",
            name="bev_projection_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/bev_projection.yaml"]),
            ],
            remappings=[
                ("seg_mask", "/seg/mask"),
                ("depth_dense", "/depth/dense"),
                ("elevation_map", "/elevation_map"),
                ("bev_semantic_grid", "/bev/semantic_grid"),
            ],
        ),
        ComposableNode(
            package="traversability_generator",
            plugin="traversability_generator::CostmapFusionNode",
            name="costmap_fusion_node",
            namespace="",
            parameters=[
                {"use_sim_time": use_sim_time},
                PathJoinSubstitution([pkg_share, "config/params/costmap_fusion.yaml"]),
            ],
            remappings=[
                ("bev_semantic_grid", "/bev/semantic_grid"),
                ("elevation_map", "/elevation_map"),
                ("traversal_costmap", "/costmap/traversal"),
                ("elevation_out", "/elevation_map/output"),
            ],
        ),
    ]

    container = ComposableNodeContainer(
        name="traversability_container",
        namespace="",
        package="rclcpp_components",
        executable="component_container",
        composable_node_descriptions=composable_nodes,
        output="screen",
    )

    return LaunchDescription([
        use_sim_time_arg,
        rmw_impl,
        cyclone_cfg,
        container,
    ])
